### ISSUE TITLE
lwsl_warn format error

### ISSUE THREAD

**Issue by MZachmann** [marcoevang/camilladsp-setrate#1]
Hi, I'm getting what I think is an appropriate error in setrate_lws.c line 203 where the format statement has three %s entries but only two data items. Thanks for this app, i'm looking forward to using it.

**Comment by marcoevang** [comment]
You are right. I am about to upload a slightly improved version that includes fixing the error you report.
Thanks for pointing it out for me.

**Comment by marcoevang** [comment]
A new version of source files has been uploaded.
This version includes fixing of bug reported by @MZachmann, as well as minor improvements.
